spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/travel_agency?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
